apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-runner
rules:
  - apiGroups: ['kustomize.toolkit.fluxcd.io']
    resources: ['kustomizations']
    verbs: ['list', 'patch', 'watch', 'update', 'get']