apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notification-provider-alert
  namespace: flux-system
spec:
  providerRef:
    name: notification-provider
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
    - kind: GitRepository
      name: '*'