apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source
    namespace: flux-system
  path: ./Sample4/clusters/cluster-1/apps/
  prune: true
  wait: true
  suspend: false
  timeout: 10m
  # postBuild:
  #   substitute:
  #     acr: "prod"
