apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: gitops-demo
    namespace: flux
  path: ./Sample4/clusters/cluster-1/infra/
  prune: true
  suspend: false
  wait: true
  timeout: 10m
