apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-permissions
  namespace: flux-system
subjects:
- kind: ServiceAccount
  name: flux-applier
  apiGroup: ""
roleRef:
 kind: Role
 name: flux-permissions
 apiGroup: ""